module: MaterialMotionTransitions
module_version: 1.1.0
umbrella_header: src/MaterialMotionTransitions.h
objc: true
sdk: iphonesimulator
github_url: https://github.com/material-motion/transitions-objc
github_file_prefix: https://github.com/material-motion/transitions-objc/tree/v1.1.0
